apiVersion: v1
kind: ConfigMap
metadata:
  name: <name>-configmap
  namespace: <namespace>
  labels:
    app: <name>
data:                                 #here we can define the data
  mapRoles:                           # using map we can map masters group with username and rolearn 
    - "groups":
      - "system:masters"
      "rolearn": ""
      "username": ""
  mapUsers:
    - "groups":
      - "system:masters"
        "userarn": ""
        "username": ""
immutable: false                      # this data can be changed as it is mutable