apiVersion: v1
data:
  inscure: true
  password: 
  project:
  type: git
  url:
  username:
kind: Secrect
metadata:
  labels:
    app:
  name: <name>-secret
  namespace: <namespace>
type: Opaque

---

# we can give config.json in secrect

{
  "auths" : {
    "https://<artifactory>" : {
      "auth": "username:password"                #vinod.jaladanki:<password> this should be in base64 encoded
      "email": "cyberwizard94@gmail.com"
    }

  }
}

# use this to encrypt cat config.json | base64

apiVersion: v1
data:
  config.json: <base64 output of file config.json>
kind: Secrect
metadata:
  labels:
    app:
  name: <name>-secret
  namespace: <namespace>