---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: as-service-account
  namespace: default

  ---
apiVersion: v1
kind: Secret
metadata:
  name: secret-as-service-account
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "as-service-account"
type: kubernetes.io/service-account-token